### ISSUE TITLE
superfluous comma at the end of arrays and objects

### ISSUE THREAD

**Issue by viebel** [thejameskyle/pretty-format#56]
`[1,2,3]` is formatted as:
```
Array [
  1,
  2,
  3,
]
```

`{a: 1}` is formatted as:
```
Object {
  "a": 1,
}
```

**Comment by cpojer** [comment]
This is recommended in JavaScript so that code changes when adding an item to the end of a list don't show up as two line changes (adding a new line vs. adding a comma + a new line) and is considered a best practice. We also do this in pretty format, mostly because the format is used in Jest snapshots. We will not be changing this.
